# fly.toml app configuration file generated for sotama-keeper-devnet on 2026-05-08T20:32:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sotama-keeper-devnet'
primary_region = 'iad'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  CLUSTER = 'devnet'
  FEE_TOPUP_AMOUNT_LAMPORTS = '100000'
  FEE_TOPUP_SCAN_INTERVAL_SECS = '300'
  FEE_TOPUP_THRESHOLD_LAMPORTS = '50000'
  HELIUS_DEVNET_RPC = 'https://devnet.helius-rpc.com'
  HELIUS_DEVNET_SENDER = 'https://devnet.helius-rpc.com/?api-key=__APIKEY__'
  HELIUS_DEVNET_WS = 'wss://atlas-devnet.helius-rpc.com'
  JUPITER_BASE_URL = 'https://api.jup.ag'
  KEEPER_FEE_LAMPORTS = '5000'
  PRICE_POLL_INTERVAL_SECS = '12'
  PROGRAM_ID = '2gp9bMBEVpQp6Lyyg13Bw6XF9S9saAcm9C4XQ69T8ZqQ'
  PYTH_HERMES_URL = 'https://hermes.pyth.network'
  RECONCILE_INTERVAL_SECS = '60'
  RUST_LOG = 'info,sotama_keeper=debug'
  SHARD_SIZE = '40'
  STAKE_POLL_INTERVAL_SECS = '60'
  SWAP_SLIPPAGE_BPS = '50'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
