export type TimeRegime =
  | "US_EQUITY_REGULAR"
  | "US_EQUITY_PREMARKET"
  | "US_EQUITY_POSTMARKET"
  | "US_EQUITY_OVERNIGHT"
  | "US_EQUITY_WEEKEND"
  | "METAL_ACTIVE"
  | "METAL_MAINTENANCE"
  | "METAL_WEEKEND"
  | "CRYPTO_NORMAL"
  | "CRYPTO_HIGH_VOL";

export const TIME_REGIMES: readonly TimeRegime[] = [
  "US_EQUITY_REGULAR",
  "US_EQUITY_PREMARKET",
  "US_EQUITY_POSTMARKET",
  "US_EQUITY_OVERNIGHT",
  "US_EQUITY_WEEKEND",
  "METAL_ACTIVE",
  "METAL_MAINTENANCE",
  "METAL_WEEKEND",
  "CRYPTO_NORMAL",
  "CRYPTO_HIGH_VOL",
];
